In [4]:
%load_ext autoreload
%autoreload
import sys
sys.path.append('../Source')
from SQLParser import *
from JoinGraphUtils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
SQLGrammar = getSQLGrammar()

In [ ]:
sqlParse = SQLGrammar.parseString("SELECT * FROM a, b as banana, c as cat WHERE a.col is not null AND a.col2 = 4;")

In [ ]:
sqlParse[0]['where'][0][1][0]

In [22]:
joinQueries = SQLQueriesToJoinQueryGraphs("SELECT * FROM a, b as banana, c as cat WHERE a.col=b.col AND a.col is null AND b.col=c.col AND b.col2 LIKE 'apple' AND b.col2 = 100 AND b.col3 IN [1,2,3];")

[([1], {}), ([2], {}), ([3], {})]

In [23]:
for joinQuery in joinQueries:
    joinQuery.printJoinGraph()

A is the 1th joined table with predicates: COL IS NULL
A joins with B on column COL
A joins with C on column COL
B is the 2th joined table with predicates: COL2 LIKE 'apple' COL2 = 100 COL3 IN (1, 2, 3)
B joins with C on column COL
B joins with A on column COL
C is the 3th joined table with predicates:
C joins with B on column COL
C joins with A on column COL

[1, 2, 3]

In [7]:
StatQueries = SQLFileToJoinQueryGraphs('../Workloads/StatsQueries.sql')
SQLQueries = SQLFileToSQLStatements('../Workloads/StatsQueries.sql')

"\nSELECT * FROM comments as c, posts as p, postLinks as pl WHERE c.UserId = p.OwnerUserId AND p.Id = pl.PostId AND p.CommentCount<=18 AND p.CreationDate>='2010-07-23 07:27:31'  AND p.CreationDate<='2014-09-09 01:43:00' "

In [ ]:
Counter = 0
for i in range(len(JOBQueries)):
    Counter += 1
    print("Query: " + str(Counter))
    print(SQLQueries[i])
    print(JOBQueries[i].getSQLQuery())
    print(JOBQueries[i].tableDict)

In [6]:
sizes = ResultsFileToSizes("../Workloads/JOBLightRangesSizes.txt")

ovie_companies,movie_info_idx,title#title.id=movie_companies.movie_id,movie_companies.movie_id=movie_info_idx.movie_id#title.kind_id,=,2,title.series_years,>=,2004-2008,title.production_year,<=,2004.0#11637

In [7]:
sizes

[11637,
 383,
 79017,
 6167,
 91761,
 266208,
 293277,
 3014,
 37797,
 154286,
 50805,
 33,
 2,
 711,
 74486,
 158431,
 372,
 2362,
 36816,
 9552,
 5380,
 828,
 11091,
 142270,
 7,
 3,
 9,
 6,
 12368,
 128,
 27753,
 2562,
 88620,
 163824,
 112070,
 1110,
 30990,
 6304,
 274616,
 152818,
 168856,
 57841,
 13480,
 296250,
 141823,
 39346,
 3529,
 4509,
 28307,
 3,
 18602,
 32106,
 1644,
 3476,
 55272,
 1286,
 16315,
 23,
 26,
 188,
 14,
 76294,
 14534,
 300,
 5577,
 13,
 10,
 174,
 341,
 2375,
 76,
 2601,
 15764,
 3025,
 4475,
 1090,
 4,
 645,
 1149,
 29,
 82,
 4577,
 2124,
 1,
 37,
 1,
 34,
 815,
 2771,
 298,
 15,
 287,
 307,
 7856,
 9209,
 509688,
 4327,
 64,
 32961,
 29,
 20,
 79,
 22,
 1179,
 5,
 53,
 1520,
 2001,
 2176,
 46,
 27,
 10320,
 40,
 25615,
 199,
 5053,
 79,
 678178,
 9128,
 59,
 3347,
 19130,
 99,
 695,
 5,
 8,
 17020,
 43,
 1399,
 6594972,
 23,
 56888,
 23150,
 8714,
 55,
 571,
 3,
 28815,
 165076309,
 219,
 1207,
 11770123,
 1,
 27561,
 38,
 46338,
 227,
 28600,
 55,
 1,
 64,
 250,
 5,
 4,
 585,
 567,
 78,
 27816,
 2,
 854261,
 11838094,
 4006,
 1670,
 4791,
 4137,
 229,
 3,
 2802,
 4054,
 1,
 6,
 23796,
 31478,
 11,
 46701,
 6,
 60,
 18,
 197,
 317,
 76,
 12,
 3,
 1,
 1,
 3,
 8748,
 8,
 4009,
 62,
 4,
 62,
 4774,
 12,
 3,
 2664,
 102,
 6,
 526,
 131,
 3,
 3,
 854464,
 39,
 3,
 264460,
 193,
 447,
 21,
 3,
 43,
 1500007,
 3365,
 65912,
 1,
 5,
 4,
 184,
 1,
 1,
 38679,
 3819244,
 164618,
 5476,
 3862,
 1290161,
 840,
 60,
 459123,
 1,
 185404,
 4093857,
 32826,
 1512,
 360,
 3820,
 211104,
 1230,
 12032087,
 2,
 5805,
 500819,
 181760,
 1253083,
 19155456,
 6671,
 20791964,
 50106,
 89274,
 52484,
 295,
 6835697,
 118,
 62370,
 21619637,
 1858,
 110469,
 14072,
 354654,
 239635,
 108747,
 444310,
 1471264,
 4077027,
 45,
 12792,
 5456,
 2168,
 910,
 19,
 147596,
 12692472,
 6191,
 59795,
 2972716,
 2199,
 439305,
 1086,
 27,
 25,
 534,
 46,
 1975,
 6,
 639867,
 4,
 4,
 5,
 18104361,
 590,
 122,
 6339,
 23,
 77,
 4,
 14,
 782663,
 4,
 6795326,
 1136,
 1251,
 2526,
 1515,
 1438,
 59357,
 3271,
 2800839,
 567,
 2,
 10383,
 9134437,
 38,
 3,
 1845302,
 658076,
 8740,
 102,
 4341,
 454987,
 1915,
 64219,
 11267677,
 1,
 5561348,
 1230,
 1137,
 43091912,
 23,
 39,
 677,
 570565,
 13899,
 1417,
 1119,
 1,
 1194786,
 5454544,
 509582,
 351140,
 195931,
 6238,
 5906,
 304411,
 23481,
 1280191,
 382026,
 590,
 21,
 50968,
 18,
 1429,
 3340861,
 2,
 1729301,
 2454483,
 218996,
 1,
 11519,
 252274,
 533889,
 17410,
 390343,
 8,
 18,
 298,
 425101,
 122854,
 5812,
 3,
 18,
 70,
 11,
 48,
 55,
 50503,
 282576,
 7,
 3928,
 91717,
 3077,
 3692856,
 4,
 5,
 724787,
 1453899,
 16494,
 66,
 21004,
 61314,
 6517182,
 1184773,
 37,
 91025,
 6598,
 2914,
 4,
 24827,
 3419841,
 26948,
 280643,
 2351543,
 60,
 643858,
 17,
 198102,
 244474,
 4021,
 373,
 976,
 1549,
 138855,
 74412,
 2634,
 88511,
 7557053,
 180,
 3010052,
 580951,
 1154208,
 144362,
 94207,
 7183702,
 292,
 3474327,
 13625942,
 441793,
 541,
 366342,
 4621,
 12,
 386013,
 1717,
 1460,
 162018,
 9582521,
 1034888,
 351,
 66067,
 1058654,
 25939,
 3245,
 945,
 264,
 18875160,
 7316806,
 12548,
 22447677,
 7513305,
 1495,
 763746,
 1797,
 506397,
 2919068,
 37563,
 8123586,
 188668,
 163003,
 13146,
 2500526,
 272419,
 57,
 409330,
 1785,
 270205,
 3153,
 1640,
 3881432,
 6525723,
 210356,
 21645,
 1119479,
 13143,
 4032,
 550115,
 624,
 30464,
 568,
 917942,
 1809,
 10907,
 70768,
 2587182,
 2027,
 464136,
 438683,
 1176,
 176,
 1525,
 42,
 1248132,
 2290592,
 28070,
 204,
 537103,
 18660,
 1,
 13,
 261428,
 3,
 61,
 1,
 55,
 1275,
 42,
 2598743,
 461584,
 11122353,
 3968450,
 38669,
 336,
 10909,
 477,
 9374,
 132,
 372329,
 204393225,
 85,
 159,
 30,
 5036,
 26352,
 2345,
 173540809,
 472,
 30,
 8968,
 1500,
 2625519,
 990584,
 5275,
 15,
 7324,
 2702174,
 55,
 13402896,
 108108,
 13588,
 22,
 97,
 163,
 5542,
 17,
 784,
 177,
 120,
 21,
 46,
 212,
 583802,
 4,
 53362,
 2199970,
 1383,
 12564,
 251627293,
 2623,
 8430043,
 27269086,
 6751,
 16568,
 207700,
 230,
 482765,
 3746804,
 2404075,
 6120,
 9980,
 1786,
 1560371,
 417,
 4116,
 615,
 29701,
 8169,
 1590,
 914262,
 8144875,
 2573,
 12,
 128104,
 690586,
 20,
 495,
 2175,
 337418,
 37516,
 10127,
 18812369,
 47510,
 345984,
 31111320,
 7270877,
 209258,
 48,
 39519304,
 16740740,
 45298,
 25052055,
 37128,
 3361,
 3367,
 43830,
 1648,
 34508064,
 576,
 18826,
 4408,
 1115511,
 172434659,
 620,
 29501,
 2866481,
 832,
 8461034,
 3864,
 51147544,
 18155630,
 1178,
 138562,
 4050,
 25935,
 1035,
 43837,
 213413,
 256,
 5306,
 82602,
 1054186,
 72,
 93727,
 7482,
 251648,
 4544,
 2803,
 1280,
 1848563,
 234208032,
 14989,
 12143,
 58,
 87249229,
 608073,
 750172,
 2793775,
 5826,
 9870,
 65,
 20746,
 179557,
 110867,
 300,
 1043,
 113980,
 180907,
 923,
 398958,
 1841791,
 31705797,
 167475,
 2276,
 552,
 188771,
 12079848,
 517247,
 7927570,
 52501155,
 325683,
 1751786,
 1049613,
 11699947,
 9783,
 46766,
 270854,
 5513,
 46395,
 4866,
 252,
 119,
 147747,
 30786669,
 287514,
 1143354,
 1991995,
 27862382,
 887433,
 4955570,
 4886992,
 881912,
 420,
 2370230,
 1082497,
 1260,
 18150,
 423101,
 2722,
 2724,
 2403297,
 15047713,
 31857,
 165205,
 1376795,
 308278,
 3499923,
 936,
 207367,
 3194664,
 145646247,
 330,
 3079,
 101947,
 12813162,
 372,
 19071,
 84704346,
 2,
 229874,
 156062949,
 110458,
 70255280,
 300534,
 95934191,
 2978718,
 1594304,
 278288,
 278167027,
 106916359,
 376253,
 27584135,
 33835390,
 3656131,
 12258219,
 1908816,
 256073,
 279890549,
 50336850,
 41360320,
 3879439,
 5122149,
 44428153,
 165340436,
 11985049,
 172260,
 13343126,
 276159297,
 1388213,
 1880588402,
 7165068,
 36106032,
 42428117,
 3946377,
 10069,
 31210542,
 6420559,
 3615154,
 1678,
 2565,
 3049736,
 21359567,
 4104534,
 19488,
 7743602,
 80435756,
 217826874,
 60435,
 255019,
 127228,
 398104,
 18825451,
 1375369013,
 48342,
 136277,
 2422716476,
 6090598,
 182,
 115449479,
 112377,
 324,
 12919414,
 2464368142,
 136139256,
 75133,
 394,
 1034,
 11128,
 34200,
 286941,
 291055812,
 96878,
 1458679,
 982411246,
 193639063,
 4917616,
 3241671,
 1398,
 37995,
 37945282,
 146796,
 6085577,
 768,
 2185,
 598658181,
 1889972,
 211010863,
 16688,
 4566429,
 10387049239,
 323629521,
 1427503,
 18613,
 648,
 121580,
 1150713,
 2185795,
 3791838,
 360636,
 9599423,
 7629,
 9838909,
 6305,
 470860,
 635109488,
 2560,
 14226867,
 241979917,
 1385,
 62040,
 3465,
 1994417,
 16490118607,
 2715175754,
 876156815,
 112405384,
 145610825751,
 87552684015,
 2000469384,
 8509982,
 71510612,
 2942914169,
 233657819759,
 59786834223,
 28048361,
 18914961759,
 37119,
 321778,
 8829,
 6417433,
 110783530297,
 1180917,
 3566861,
 240912,
 26816550812,
 237378060,
 3257859,
 3783190464,
 12685441,
 304420,
 32943,
 24318,
 5497801,
 9418905996,
 54920442225,
 127446634,
 66197334156,
 43905290162,
 1838552,
 2154,
 67952,
 3296160,
 12497023,
 47441026,
 506912,
 27959701,
 53915,
 4501590,
 130650,
 1504602,
 202920,
 90812,
 220,
 11222,
 6158827704,
 16974,
 95697536,
 477796,
 2805,
 47110,
 1429981,
 855960144,
 7173609623,
 2604,
 212573,
 2775,
 33447,
 151093,
 7209924,
 4582278,
 25365,
 32012217,
 1623,
 517836,
 699782,
 3333411,
 50398707,
 9742,
 375,
 1279044537,
 343962,
 1382057,
 2,
 22644,
 4144,
 179496,
 9768,
 69463,
 2970,
 137970,
 441052,
 2240,
 133788040,
 996880,
 191313,
 231705774,
 69372,
 108757563,
 772249213,
 726,
 11501,
 67815,
 22120,
 42,
 41144,
 11391027,
 42945,
 175942,
 39296392,
 26604,
 1654,
 5101948,
 231,
 503,
 14286000,
 37,
 384426,
 84,
 34526,
 46,
 4953,
 1191,
 4,
 10334,
 15276,
 106248,
 1,
 1,
 44930,
 1,
 9,
 132,
 17622,
 4422,
 735,
 4426965,
 7,
 36296,
 77803274,
 38060,
 6525,
 108,
 42,
 1488,
 258,
 188,
 34216,
 130,
 49329,
 45609,
 27,
 3279,
 159,
 1101,
 560,
 10,
 657412,
 53679,
 4707,
 1164,
 6127,
 62,
 65,
 1449836,
 43698,
 391,
 1185583,
 36,
 95550,
 1454,
 723,
 22,
 12,
 4749]